import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface-container-low": "#f3f4f5",
        "surface-container-highest": "#e1e3e4",
        "tertiary-fixed": "#ffdcc6",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-fixed-variant": "#004395",
        error: "#ba1a1a",
        "on-secondary-container": "#405682",
        "on-primary-container": "#fefcff",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#304671",
        "on-error": "#ffffff",
        primary: "#0058be",
        "surface-container-high": "#e7e8e9",
        "surface-bright": "#f8f9fa",
        surface: "#f8f9fa",
        "on-tertiary-container": "#fffbff",
        "on-background": "#191c1d",
        "on-surface-variant": "#424754",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1d",
        "surface-variant": "#e1e3e4",
        "secondary-fixed-dim": "#b1c6f9",
        "primary-fixed": "#d8e2ff",
        "on-tertiary-fixed-variant": "#723600",
        "secondary-container": "#b6ccff",
        "primary-fixed-dim": "#adc6ff",
        "primary-container": "#2170e4",
        "surface-tint": "#005ac2",
        "surface-dim": "#d9dadb",
        "inverse-primary": "#adc6ff",
        "secondary-fixed": "#d8e2ff",
        "inverse-surface": "#2e3132",
        "on-tertiary-fixed": "#311400",
        outline: "#727785",
        "on-secondary-fixed": "#001a42",
        "tertiary-fixed-dim": "#ffb786",
        "tertiary-container": "#b75b00",
        "on-tertiary": "#ffffff",
        "surface-container": "#edeeef",
        background: "#f8f9fa",
        tertiary: "#924700",
        "outline-variant": "#c2c6d6",
        "on-primary-fixed": "#001a42",
        secondary: "#495e8a",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      keyframes: {
        scan: {
          "0%": { top: "10%" },
          "50%": { top: "90%" },
          "100%": { top: "10%" },
        },
      },
      animation: {
        scan: "scan 3s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
export default config;
